#!/bin/sh
#
# jsonstatsd daemons shit yeah
#
# chkconfig: 2345 20 80
# description: start and stop the jsonstats daemon

### BEGIN INIT INFO
# Provides: jsonstatsd
# Required-Start: network
# Required-Stop: 
# Short-Description: start and stop the jsonstats daemon
# Description:      start and stop the jsonstats daemon
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/jsonstatsd"
prog="jsonstatsd"
#config="<path to major config file>"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
#    [ -f $config ] || exit 6
    echo -n $"Starting $prog:"
    daemon $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?




# #!/bin/bash
# set -x
# #
# # jsonstatsd	Starts, stops and restarts the json system stats daemon
# #
# # chkconfig:   - 98 01
# # description: 
# # processname: jsonstatsd
# # pidfile: /var/run/jsonstatsd.pid

# ### BEGIN INIT INFO
# # Provides: jsonstatsd
# # Should-Start: $network
# # Description: 
# # Short-Description: 
# ### END INIT INFO

# # Source function library.
# . /etc/init.d/functions


# display_name="JsonStatsd"
# exec="/usr/bin/jsonstatsd"
# prog="jsonstatsd"
# prog_user="jsonstatsd"

# [ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

# lockfile=/var/lock/subsys/$prog

# # --user www-data --group www-data
# # --chuid www-data


# start() {
#     echo -n "Starting ${prog}"
#     ${exec}
#     touch ${lockfile}
#     return 0
# }


# stop() {
#     echo -n "Stopping ${prog}"
#     killproc ${prog}
#     rm -f ${lockfile}
#     return 0
# }


# restart() {
#     :
# }


# rh_status() {
#     status ${prog}
# }

# case "$1" in
#     start)
#         rh_status && exit 0
#         $1
#         ;;
#     stop)
#         rh_status || exit 0
#         $1
#         ;;
#     restart)
#         $1
#         ;;
#     status)
#         rh_status
#         ;;
#     *)
#         echo $"Usage: $0 {start|stop|status|restart}"
#         exit 2
# esac
# exit $?
